version: '3'

services:
  web-service:
    container_name: web-service
    build: .
    image: web-service:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - APP_NAME=github
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=11111111
      - DB_NAME=golang
      - DATABASE_URL=postgres://postgres:11111111@db:5432/golang?sslmode=disable
    networks:
      - custom-network

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111111
      POSTGRES_DB: golang
    ports:
      - "5433:5432"
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
